### ISSUE TITLE
Change the instance names

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/engine-test#1]
I know that the instance names have special meanings, but it's soooo hard to find their names in the composition directory. The things are even complicated when debugging a bug in the builder... :boom:

**Comment by adioo** [comment]
@IonicaBizau What names do you propose?

**Comment by IonicaBizau** [comment]
Event adding a unique prefix would make the life easier. Something like:

 - `A_E-...`
 - `B_E-...`
 - `C_E-...`
 - `D_E-...`
  - ...

**Comment by adioo** [comment]
Think this is obsolete with the latest changes in engine.
